"""Remove plot entity

Revision ID: f78e2bbafc27
Revises: 4aa1cbccf7f0
Create Date: 2021-05-05 10:44:31.017756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78e2bbafc27'
down_revision = '4aa1cbccf7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plot')
    op.add_column('image', sa.Column('pred_img_path', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_image_pred_img_path'), 'image', ['pred_img_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_pred_img_path'), table_name='image')
    op.drop_column('image', 'pred_img_path')
    op.create_table('plot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###
